config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'spots#index'
  resources :spots
  resources :users, only: [:show, :edit, :update]
  resources :spots do 
    resources :comments, only: [:create]
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :spot
end

app/models/spot.rb
class Spot < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :place, presence: true
  validates :address, presence: true
  validates :one_word, presence: true
  validates :thought, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many  :spots, dependent: :destroy
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.create(comment_params)
    redirect_back(fallback_location: root_path)
  end

  private
  def comment_params
    params.require(:comment).permit(:comment_content, :spot_id)
  end 
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
    
  def index
    @spots = Spot.order("created_at DESC").page(params[:page]).per(6)
  end

  def show
    @spot = Spot.find(params[:id])
    @comments = @spot.comments
    @comment = current_user.comments.new
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(spot_params)
    if @spot.save
      redirect_to root_path
    else
      render action: :new
    end 
  end 

  def edit 
    @spot = Spot.find(params[:id])
  end 

  def update
    @spot = Spot.find(params[:id])
    if @spot.update(spot_params)
      render action: :update
    else
      render action: :edit
    end 
  end 

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
  end 

  private
  def spot_params
    params.require(:spot).permit(:place, :address, :one_word, :thought, :image).merge(user_id: current_user.id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  def show
    @user = User.find(params[:id])
    @spots = @user.spots.order("created_at DESC").page(params[:page]).per(6)
  end 

  def edit 
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
  end 

  private
  def user_params
    params.require(:user).permit(:name, :from, :age, :image)
  end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Traveler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
    <% if user_signed_in? %>
      <% unless %w[new_user_session new_user_registration].any? { |name| current_page?(send("#{name}_path")) } %> 
      <header class="header">
        <div class="header-menu">
          <div class="header-menu-content">
            <div class="header-menu-items">
              <ul class="header-menu-space">
                <li class="header-menu-btn">
                  <%= link_to "投稿する",new_spot_path, class: "new-form-btn btn" %>
                </li>
                <li class="header-menu-btn">
                  <%= link_to "ホームへ戻る", root_path, class: "home-btn btn" %>
                </li>
                <li class="header-menu-btn">
                  <%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "header-sign-out-btn btn" %>
                </li>
                <li class="header-menu-btn">
                  <%= link_to "マイページ",user_path(current_user) , class: "header-mypage-btn btn" %>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="header-content">
          <h1 class="main-title">
            <%= link_to "Traveler", root_path ,class: "main-title-buttun" %>
          </h1>
          <p class="site-description">
            さまざまな旅行先を
            <br>
            皆に共有しよう！
          </p>
        </div>
      </header>
      <% end %>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/spots/_spot.html.erb
<div class="loop-article">
  <h2 class="area">
    <a class="area-description" href ="/spots/<%= spot.id %>" >
      <%= spot.place %>
    </a> 
  </h2>
  <div class="image-space">
    <a class="image-buttom" href="/spots/<%= spot.id %>">
    <% if spot.image.attached? %>
      <%= image_tag spot.image, class: "top-image" %>
    <% end %>
    </a>
  </div>
  <p class="sab-text">
    <a href="/spots/<%= spot.id %>" class="sab-text-class">
      <%= spot.one_word %>
    </a>
  </p>
</div>

app/views/spots/destroy.html.erb
<div class="new-main">
  <div class="new-content">
    <p class="page-title">
      Delete
    </p>
    <h1 class="subtitle">
      削除
    </h1>
  </div>
  <div class="wide-content-article">
    <article class="article">
      <p class="article-content">
      </p>
      <br class="clear">
      <div class="wpcf7">
        <p class="update-form">
          削除が完了しました。
        </p>
        <div class="update">
          <%= link_to "ホームへ", root_path, class: "update-form-btn" %>
        </div>
      </div>
    </article>
  </div>
</div>

app/views/spots/edit.html.erb
<div class="new-main">
  <div class="new-content">
    <p class="page-title">
      Edit
    </p>
    <h1 class="subtitle">
      編集
    </h1>
  </div>
  <div class="wide-content-article">
    <article class="article">
      <p class="article-content">
      </p>
      <br class="clear">
      <div class="wpcf7">
      <div class="error-form">
        <%= form_for(@spot) do |f| %>
        <% if @spot.errors.any? %>
              <h3 class="error">
                入力した内容にエラーが<%= @spot.errors.count %>件あります
              </h3>
              <ul class="error-point">
                <% @spot.errors.full_messages.each do |message| %>
                  <li class="error-point-item">
                    <p class="message">
                      <%= message %>
                    </p>
                  </li>
                <% end %>
              </ul>
            <% end %>
            </div>
          <div class="place-space">
            <%= f.label :place, "場所名", {class: 'place-logo'} %>
            <%= f.text_field :place,:placeholder => "例: 東京スカイツリー", class: "place" %>
          </div>
          <div class="address-space">
            <%= f.label :address, "場所", {class: 'address-logo'} %>
            <%= f.text_area :address,:placeholder => "例:　東京都墨田区", class: "address" %>
          </div>
          <div class="impression-space">
            <%= f.label :one_word, "ひとこと", {class: 'impression-logo'} %>
            <%= f.text_field :one_word,:placeholder => "例:　見上げた迫力がすごい", class: "impression" %>
          </div>
          <div class="thought-space">
            <%= f.label :thought, "感想", {class: 'thought-logo'} %>
            <%= f.text_area :thought,:placeholder => "自分が思ったことを何でもいいので書いてください。", class: "thought" %>
          </div>
          <div class="image-area">
            <%= f.label :image, "写真", {class: 'image-logo'} %>
            <%= f.file_field :image, class: "image" %>
          </div> 
          <div class="send">
            <%= f.submit  "Send", class: "send-buttom" %>
          </div>
        <% end %>
      </div>
    </article>
  </div>
</div>

app/views/spots/index.html.erb
<div class="main">
  <div class="main-content">
     <div class="wide-content">
      <div class="loop">
        <% @spots.each do |spot| %>
          <%= render partial: "spots/spot", locals: { spot: spot  } %>
         <% end %>
      </div>
      <%= paginate @spots %>
     </div>
  </div>
</div>

app/views/spots/new.html.erb
<div class="new-main">
  <div class="new-content">
    <p class="page-title">
      New post
    </p>
    <h1 class="subtitle">
      <div class="erroer-form">
      新規投稿
    </h1>
  </div>
  <div class="wide-content-article">
    <article class="article">
      <p class="article-content">
      </p>
      <br class="clear">
      <div class="wpcf7">
        <div class="error-form">
          <%= form_for(@spot) do |f| %>
            <% if @spot.errors.any? %>
              <h3 class="error">
                入力した内容にエラーが<%= @spot.errors.count %>件あります
              </h3>
              <ul class="error-point">
                <% @spot.errors.full_messages.each do |message| %>
                  <li class="error-point-item">
                    <p class="message">
                      <%= message %>
                    </p>
                  </li>
                <% end %>
              </ul>
            <% end %>
          </div>
          <div class="place-space">
            <%= f.label :place, "場所名", {class: 'place-logo'} %>
            <%= f.text_field :place,:placeholder => "例: 東京スカイツリー", class: "place" %>
          </div>
          <div class="address-space">
            <%= f.label :address, "場所", {class: 'address-logo'} %>
            <%= f.text_area :address,:placeholder => "例:　東京都墨田区", class: "address" %>
          </div>
          <div class="impression-space">
            <%= f.label :one_word, "ひとこと", {class: 'impression-logo'} %>
            <%= f.text_field :one_word,:placeholder => "例:　見上げた迫力がすごい", class: "impression" %>
          </div>
          <div class="thought-space">
            <%= f.label :thought, "感想", {class: 'thought-logo'} %>
            <%= f.text_area :thought,:placeholder => "自分が思ったことを何でもいいので書いてください。", class: "thought" %>
          </div>
          <div class="image-area">
            <%= f.label :image, "写真", {class: 'image-logo'} %>
            <%= f.file_field :image, class: "image" %>
          </div> 
          <div class="send">
            <%= f.submit  "Send", class: "send-buttom" %>
          </div>
        <% end %>
      </div>
    </article>
  </div>
</div>

app/views/spots/show.html.erb
<div class="new-main">
  <div class="new-content">
    <h2 class="throw-spot">
      <a href="/users/<%= @spot.user.id %>" class="thorw-spot-btn">
        <%= @spot.user.name %>
      </a>
      <span>
        さんの投稿
      </span>
    </h2>
    <h1 class="show-place-content">
      <%= @spot.place %>
    </h1>
    <h1 class="show-one-word-content">
      <%= @spot.one_word %>
    </h1>
  </div>
  <div class="show-address">
    <p class="show-address-content">
      <%= @spot.address %>
    </p>
  </div>
  <div class="wide-content-article">
    <div class="show-content">
      <div class="show-image">
        <%= image_tag @spot.image, class: "sab-image" %>
      </div>
      <p class="show-thought">
        <%= @spot.thought %>
      </p>
    </div>
  </div>
  <% if current_user.id == @spot.user.id %>
  <div class="btn-area">
    <ul class="btn-space">
      <li class="btn-space-edit show-btn">
        <%= link_to '編集', "/spots/#{@spot.id}/edit", class: "show-edit-btn" %>
      </li>
      <li class="btn-space-delete show-btn">
        <%= link_to '削除', "/spots/#{@spot.id}", method: :delete, class: "show-delete-btn" %>
      </li>
    </ul>
  </div>
  <% end %>
  <div class="comment-area">
    <div class="comment-form">
      <%= form_with(model:[@spot, @comment], method: :post, class: "comment-main-form") do |f| %>
        <%= f.text_area :comment_content, class: "comment-form-area" %>
        <%= f.hidden_field :spot_id, value: @spot.id %>
        <%= f.submit 'コメントする', class: "comment-form-btn" %>
      <% end %>
    </div>
    <div class="comment-display">
      <h2 class="comment-title">
        コメント一覧
      </h2>
      <% unless @comments.present? %>
        <p class="comment-nil">
          ※　まだコメントはありません
        <p>
      <% else %>
        <div class="comment-items">
          <% @comments.each do |comment| %>
            <p class="comment-core">
            <% if comment.user.image.attached? %>
              <%= image_tag comment.user.image, class: "comment-user-image" %>
            <% end %>  
              <span class="comment-user">
                <%= comment.user.name %>:
              </span>     
              <span class="comment-content">
                <%=  comment.comment_content %>
              </span>
            </p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/spots/update.html.erb
<div class="new-main">
  <div class="new-content">
    <p class="page-title">
      Update
    </p>
    <h1 class="subtitle">
      更新
    </h1>
  </div>
  <div class="wide-content-article">
    <article class="article">
      <p class="article-content">
      </p>
      <br class="clear">
      <div class="wpcf7">
        <p class="update-form">
          更新が完了しました。
        </p>
        <div class="update">
          <%= link_to "ホームへ", root_path, class: "update-form-btn" %>
        </div>
      </div>
    </article>
  </div>
</div>

app/views/users/edit.html.erb
<div class="new-main">
  <div class="new-content">
    <p class="page-title">
      User edit
    </p>
    <h1 class="subtitle">
      ユーザー編集
    </h1>
  </div>
  <div class="wide-content-article">
    <article class="article">
      <p class="article-content">
      </p>
      <br class="clear">
      <div class="user-wpcf7">
        <div class="error-form">
          <%= form_for(@user) do |f| %>
            <% if @user.errors.any? %>
              <h3 class="error">
                入力した内容にエラーが<%= @user.errors.count %>件あります
              </h3>
              <ul class="error-point">
                <% @user.errors.full_messages.each do |message| %>
                  <li class="error-point-item">
                    <p class="message">
                      <%= message %>
                    </p>
                  </li>
                <% end %>
              </ul>
            <% end %>
          </div>
          <div class="name-space">
            <%= f.label :name, "名前", {class: 'name-logo'} %>
            <%= f.text_field :name, class: "name-area" %>
          </div>
          <div class="from-space">
            <%= f.label :from, "出身", {class: 'from-logo'} %>
            <%= f.text_field :from, class: "from-area", placeholder: "例：東京都" %>
          </div>
          <div class="age-space">
            <%= f.label :age, "年齢", {class: 'age-logo'} %>
            <%= f.text_field :age, class: "age-area", placeholder: "例：20歳" %>
          </div>
          <div class="image-area">
            <%= f.label :image, "ユーザー写真", {class: 'image-logo'} %>
            <%= f.file_field :image, class: "image" %>
          </div> 
          <div class="user-send">
            <%= f.submit  "Send", class: "user-send-buttom" %>
          </div>
        <% end %>
      </div>
    </article>
  </div>
</div>

app/views/users/show.html.erb
<div class="new-main">
  <div class="new-content">
    <p class="page-title">
      User page
    </p>
    <h1 class="subtitle">
      ユーザーページ
    </h1>
  </div>
  <div class="wide-content-article">
    <div class="user-content">
      <div class="user-page">
        <h1 class="user-page-title">
          自己紹介
        </h1>
        <% if current_user.id == @user.id %>
        <p class="user-edit-space">
          <%= link_to '編集',edit_user_path(current_user), class: "user-edit-btn" %>
        </p>
        <% end %>
        <div class="user-image-space">
          <div class="user-items">
          <% unless @user.image.attached? %>
            <p class="force">
              ※ 画像が設定されていません
            </p>
          <% else %>
            <%= image_tag @user.image, class: "user-image"  %>
          <% end %>
          </div>
          <ul class="user-information">
            <li class="name user-core"><span class="topic">名前：</span><%= @user.name %></li>
            <li class="from user-core"><span class="topic">出身：</span><%= @user.from %></li>
            <li class="age user-core"><span class="topic">年齢：</span><%= @user.age %></li>
          </ul>
      </div>
    </div>
  </div>
</div>
<div class="main">
  <div class="main-content">
     <div class="new-wide-content">
      <div class="loop">
        <% unless @user.spots.present? %>
          <p class="spot-nil">
            ※　まだ投稿がありません
          </p>
        <% else %>
          <%= render partial: "spots/spot", collection: @spots %>
        <% end %> 
      </div>
      <%= paginate @spots %>
     </div>
  </div>
</div> 

app/views/users/update.html.erb
<div class="new-main">
  <div class="new-content">
    <p class="page-title">
      User update
    </p>
    <h1 class="subtitle">
      ユーザー更新
    </h1>
  </div>
  <div class="wide-content-article">
    <article class="article">
      <p class="article-content">
      </p>
      <br class="clear">
      <div class="wpcf7">
        <p class="update-form">
          更新が完了しました。
        </p>
        <div class="update">
          <%= link_to "マイページへ", user_path(current_user), class: "update-form-btn" %>
        </div>
      </div>
    </article>
  </div>
</div>